---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-aura-watch
  namespace: default
  labels:
    app: nexus-aura-watch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexus-aura-watch
  template:
    metadata:
      labels:
        app: nexus-aura-watch
    spec:
      containers:
      - name: n8n-monitor
        image: nexus-aura-watch:latest  # IMPORTANT: Update with your registry: your-registry/nexus-aura-watch:latest
        imagePullPolicy: Always  # Changed to Always to ensure latest image is pulled
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-aura-watch
  namespace: default
  labels:
    app: nexus-aura-watch
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: nexus-aura-watch
---
# Optional: Ingress for production
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nexus-aura-watch-ingress
#   namespace: default
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   tls:
#   - hosts:
#     - monitor.yourdomain.com
#     secretName: n8n-monitor-tls
#   rules:
#   - host: monitor.yourdomain.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: nexus-aura-watch
#             port:
#               number: 80
